name: INDEX.HTML validation
on:
  workflow_dispatch:
jobs:
  validate_index_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --save-dev w3c-html-validator - g

      - name: Validate HTML
        run: |
          npx html-validator index.html --quiet
        continue-on-error: true
