name: INDEX.HTML validation
on:
  workflow_dispatch:
jobs:
  validate_index_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install w3c-html-validator-cli -g

      - name: Validate HTML
        run: |
          w3c-validator-cli --file index.html
        continue-on-error: true

      - name: Check Validation Results
        run: |
          w3c-validator-cli --report